name: Tests

on: push

env:
  CI: 1

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm run test:full
